modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: rpm-ostree
    install:
      - autofs
      - emacs
      - fd-find
      - git
      - qt6-qtmultimedia
      - qt6-qtvirtualkeyboard
      - stow
      - zsh
    remove:
      - firefox
      - firefox-langpacks
