modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    install:
      - autofs
      - emacs
      - fd-find
      - git
      - qt6-qtmultimedia
      - qt6-qtvirtualkeyboard
      - stow
      - zsh
    remove:
      - firefox
      - firefox-langpacks

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
