---
name: leblue
description: This is my personal OS image.

base-image: quay.io/fedora-ostree-desktops/base-atomic
image-version: 42

modules:

    - type: containerfile
      snippets:
        - COPY --from=ghcr.io/ublue-os/akmods:main-42 /rpms /tmp/rpms
        - COPY --from=ghcr.io/ublue-os/akmods:main-42 /kernel-rpms /tmp/rpms/kernel
        - RUN find /tmp/rpms
        - RUN rpm -q ublue-os-akmods-addons || rpm-ostree install /tmp/rpms/ublue-os/ublue-os-akmods-addons*.rpm
    - type: script
      scripts:
        - installsignedkernel.sh

    - type: containerfile
      snippets:
        - RUN rpm-ostree install just powerstat
        - COPY --from=ghcr.io/ublue-os/config:latest /rpms/ublue-os-udev-rules.noarch.rpm /
        - COPY --from=ghcr.io/ublue-os/config:latest /rpms/ublue-os-update-services.noarch.rpm /
        - COPY --from=ghcr.io/ublue-os/config:latest /rpms/ublue-os-signing.noarch.rpm /
        - COPY --from=ghcr.io/ublue-os/config:latest /rpms/ublue-os-luks.noarch.rpm /
        - COPY --from=ghcr.io/ublue-os/config:latest /rpms/ublue-os-just.noarch.rpm /
        - RUN rpm -ivh /ublue-os-udev-rules.noarch.rpm
        - RUN rpm -ivh /ublue-os-update-services.noarch.rpm
        - RUN rpm -ivh /ublue-os-signing.noarch.rpm
        - RUN rpm -ivh /ublue-os-luks.noarch.rpm
        - RUN rpm -ivh /ublue-os-just.noarch.rpm

    - type: files
      files:
        - source: system
          destination: /

    - from-file: sddm.yml
    - from-file: base.yml
    - from-file: hyprland.yml
    - from-file: dev.yml

    - type: signing
