---
name: template
description: This is my personal OS image.

base-image: quay.io/fedora-ostree-desktops/base-atomic
image-version: 42

modules:

  - type: files
    files:
      - source: system
        destination: /

  - from-file: sddm.yml
  - from-file: base.yml
  - from-file: hyprland.yml

  - type: signing
